added reflection package
UvarovIV/Unit_Tests pull request #4
Opened 2022-07-11 17:39 UTC by UvarovIV

2022-07-11 21:12 UTC, XLelarX requested changes

2022-07-11 21:12 UTC, XLelarX commented on demo/src/test/java/com/example/reflection/WorkWithReflectionTest.java
> +    final WorkWithReflection wwrf = new WorkWithReflection();
Константа должна быть + название понятнее бы сделать

2022-07-11 21:12 UTC, XLelarX commented on demo/src/test/java/com/example/reflection/WorkWithReflectionTest.java
> +    public void workWithConstructors() throws NoSuchFieldException, IllegalArgumentException, IllegalAccessException, NoSuchMethodException, InvocationTargetException, InstantiationException {
NoSuchFieldException не используется

2022-07-12 05:58 UTC, UvarovIV commented on demo/src/test/java/com/example/reflection/WorkWithReflectionTest.java
> +    public void workWithConstructors() throws NoSuchFieldException, IllegalArgumentException, IllegalAccessException, NoSuchMethodException, InvocationTargetException, InstantiationException {
Удалил

2022-07-12 05:58 UTC, UvarovIV commented on demo/src/test/java/com/example/reflection/WorkWithReflectionTest.java
> +    public void workWithMethods() throws NoSuchFieldException, IllegalArgumentException, IllegalAccessException, NoSuchMethodException, InvocationTargetException {
Удалил

2022-07-12 05:59 UTC, UvarovIV commented on demo/src/test/java/com/example/reflection/WorkWithReflectionTest.java
> +            f -> {
Убрал

2022-07-12 05:59 UTC, UvarovIV commented on demo/src/test/java/com/example/reflection/WorkWithReflectionTest.java
> +        WorkWithReflection wwrf2 = privateConstructor.newInstance("fsdzkdks","dnjkuj");
Теперь используется

2022-07-12 05:59 UTC, UvarovIV commented on demo/src/test/java/com/example/reflection/WorkWithReflectionTest.java
> +        Field field = wwrf.getClass().getDeclaredField("privateField");
Вынес в константу

2022-07-12 05:59 UTC, UvarovIV commented on demo/src/test/java/com/example/reflection/WorkWithReflectionTest.java
> +    final WorkWithReflection wwrf = new WorkWithReflection();
Переименовал

2022-07-12 11:53 UTC, merged